### ISSUE TITLE
Swoft2.0.8下面启动有bug.

### ISSUE THREAD

**Issue by Payhon** [ctfang/swoft-admin#3]
`./vendor/ctfang/swoft-admin/src/Command/AdminCommand.php `

这个文件里面的 input()->getSript() 报错。

`./vendor/swoft/console/src/Input/Input.php  `

swoft这个类里面没有 getScript() 方法

**Comment by kylinlxl** [comment]
![111111](https://user-images.githubusercontent.com/7954154/72203297-a7a34f00-34a4-11ea-9f83-2af0b31c7190.png)

**Comment by jiangsan-legame** [comment]
![image](https://user-images.githubusercontent.com/54352584/72702616-55da8300-3b8e-11ea-8e23-fb54e4b15ef8.png)
改成`$script  = input()->getScriptFile();`就好了;希望官方更新下

**Comment by ctfang** [comment]
> ![图片](https://user-images.githubusercontent.com/54352584/72702616-55da8300-3b8e-11ea-8e23-fb54e4b15ef8.png)
> 改成`$script = input()->getScriptFile();`就好了;希望官方更新下

可以提交下pr ?

**Comment by ctfang** [comment]
0.1修复了
